import React from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const capabilities = [
  {number:'01',name:'Investment Intelligence',detail:'Research and market context, designed for informed decisions.'},
  {number:'02',name:'Portfolio Operating System',detail:'A unified view of holdings, allocation and performance.'},
  {number:'03',name:'Risk Intelligence',detail:'Understand exposure, concentration and portfolio scenarios.'},
  {number:'04',name:'Institutional Workflows',detail:'Structured proposals, human approvals and traceable outcomes.'}
];
function App(){return <><header className="nav"><a className="wordmark" href="/" aria-label="Ramptium home"><span className="mark">R</span> RAMPTIUM</a><nav aria-label="Primary"><a href="#platform">Platform</a><a href="#approach">Approach</a><a href="mailto:hello@ramptium.com?subject=Ramptium%20inquiry" className="nav-cta">Get in touch ↗</a></nav></header><main><section className="hero"><div className="eyebrow"><span className="pulse"/> THE INVESTMENT TECHNOLOGY COMPANY</div><h1>Intelligence<br/>behind <em>capital.</em></h1><p className="intro">A clearer way to understand portfolios, assess risk, and operate investment decisions — built for the people entrusted with capital.</p><div className="actions"><a className="primary" href="#platform">Explore the platform <span>↗</span></a><a className="secondary" href="#approach">Our approach ↓</a></div><div className="hero-footer"><span>RESEARCH-LED</span><span>HUMAN-GOVERNED</span><span>GLOBAL IN PERSPECTIVE</span></div></section><section id="platform" className="section"><div className="section-top"><span className="label">01 / PLATFORM</span><h2>Built for the decisions<br/>that matter.</h2><p>One connected foundation for investment understanding and operational clarity.</p></div><div className="grid">{capabilities.map(x=><article className="card" key={x.number}><span className="num">{x.number} /</span><h3>{x.name}</h3><p>{x.detail}</p><span className="arrow" aria-hidden="true">↗</span></article>)}</div></section><section id="approach" className="approach"><span className="label">02 / OUR APPROACH</span><h2>Clarity first.<br/><em>Control always.</em></h2><p>We believe technology should strengthen investment judgment, not replace accountability. Ramptium is being developed as a software and intelligence platform, with transparent analysis and human authorization at its core.</p><a href="mailto:hello@ramptium.com?subject=Ramptium%20partnership" className="primary">Discuss a partnership ↗</a></section></main><footer><span className="wordmark">RAMPTIUM</span><span>© {new Date().getFullYear()} Ramptium. All rights reserved.</span><span>Technology and research infrastructure. Not a brokerage or investment adviser.</span></footer></>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
